[tool.black]
line-length=79
exclude = '''
/(
    .git
  | .hg
  | .mypy_cache
  | .tox
  | .venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.coverage.run]
omit = ["benchmark.py", "tests/*.py", "algorithms/__init__.py", "/usr/local/lib/python3.9/*"]